// This file is autogenerated. Changes will be overwritten.
#include "Q6KNN7S663/moc_connection_manager.cpp"
#include "Q6KNN7S663/moc_telemetry_receiver.cpp"
#include "UYX5XTB5RZ/moc_hud_overlay.cpp"
#include "UYX5XTB5RZ/moc_main_window.cpp"
#include "UYX5XTB5RZ/moc_yaw_indicator.cpp"
#include "CWRUQVFSPE/moc_video_receiver.cpp"
